version: "3.8"

services:
  node_app:
    build:
      context: ./app
    container_name: node_app_2
    expose:
      - "3000"
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx_2
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node_app
    restart: always

